### ISSUE TITLE
Inference Output in C++

### ISSUE THREAD

**Issue by TranATT** [isl-org/MiDaS#123]
Hello! So I am trying to do some code in C++ for this model in tflite and after I run inference on it I modify the tensor like the example with the formula img_out = (255 * (prediction - depth_min) / (depth_max - depth_min)) (but in c++) so I was wondering if you guys know how to map those output tensor values and apply the color mapping shown in the example without using OpenCV. Thanks so much for your help!

**Comment by ranftlr** [comment]
We use the "inferno" colormap from Matplotlib for our visualizations. OpenCV does include this: https://docs.opencv.org/4.5.2/d3/d50/group__imgproc__colormap.html. If you want to avoid using OpenCV, I found this project which also has the colormap: https://github.com/tdegeus/cppcolormap

**Comment by TranATT** [comment]
Thanks so much for answering! I will take a look at it.
