### ISSUE TITLE
How to eval on MiDaS?

### ISSUE THREAD

**Issue by guangkaixu** [isl-org/MiDaS#129]
Hi, is there any evaluation code for MiDaS?

MiDaS can predict a robust inverse-depth of a single image, but how can I eval on datasets with ground truth depth like KITTI? Should I convert predict disparity to depth and evaluate in the depth space, or convert ground truth depth to disparity and evaluate in the disparity space?

I downloaded the ofﬁcial validation set of KITTI, and convert gt_depth to gt_disparity with:
```python
gt_disparity = 1 / (gt_depth + 1e-8)
gt_disparity[gt_depth==0]=0
```
after performing alignment in disparity space and evaluating on midas_v3.0_dpt-large on KITTI, I got the performance:
```
KITTI AbsRel : 10.0
KITTI delta > 1.25 : 10.1
```
It seems that my evaluation code is not so accurate. Could you please provide your evaluation code for MiDas? Thank you so much.

**Comment by AlexeyAB** [comment]
@guangkaixu To evaluate MiDaS v3.0 (DPT-Hybrid) on NYU and Kitti depth datasets using Eigen-Split, use this manual and this repository: https://github.com/isl-org/DPT/blob/main/EVALUATION.md

**Comment by guangkaixu** [comment]
@AlexeyAB Thank you for your reply. 
The evaluation code of DPT is only suitable for metric depth prediction, but MiDaS can predict monocular disparity without scale and shift. What's more, the disparity can't recover scale and shift with datasets with gt_depth like KITTI directly, so we would like to know that **how can disparity prediction recover scale and shift with gt_depth**:

1. Convert pred_disp to pred_depth.
```
pred_depth = 1 / (pred_disp + 1e-8) 
pred_depth[pred_disp <= 0] = 0
pred_depth_metric = recover_scale_shift(pred_depth, gt_depth)
error = evaluate_error(pred_depth_metric, gt_depth)
```
2. Convert gt_depth to gt_disp.
```
gt_disp = 1 / (gt_depth + 1e-8) 
gt_disp[gt_depth <= 0] = 0
pred_disp_metirc = recover_scale_shift(pred_disp, gt_disp)
error = evaluate_error(pred_disp_metirc, gt_disp)
``` 
3. Other evaluation methods...

**Comment by ranftlr** [comment]
The gists linked in the section "General-Purpose models" in https://github.com/isl-org/DPT/blob/main/EVALUATION.md show how this evaluation is done.

**Comment by guangkaixu** [comment]
Oh I see, thanks a lot!

**Comment by dreamlychina** [comment]
> Oh I see, thanks a lot!

你好，大佬问下，最后模型的输出要怎么转换才能变成米制单位的？？模型最后的输出范围太大了。

**Comment by guangkaixu** [comment]
> > Oh I see, thanks a lot!
> 
> 你好，大佬问下，最后模型的输出要怎么转换才能变成米制单位的？？模型最后的输出范围太大了。

The MiDaS can only predict affine-invariant disparity, which contains an unknown scale and an unknown shift value in the disparity area. You can align scale-shift values with np.polyfit(pred_disp, gt_disp), where gt_disp = 1 / gt_depth. Remember mask the invalid gt_depth :)

**Comment by QingshuiL** [comment]
@guangkaixu 
Hello, have you verified whether this code  https://github.com/isl-org/DPT/blob/main/EVALUATION.md can obtain the correct affine-invariant depth evaluation results? Is it okay if I use it on other models for relative depth evaluation, such as depthing anything v2?

**Comment by guangkaixu** [comment]
> @guangkaixu Hello, have you verified whether this code https://github.com/isl-org/DPT/blob/main/EVALUATION.md can obtain the correct affine-invariant depth evaluation results? Is it okay if I use it on other models for relative depth evaluation, such as depthing anything v2?

I just forget whether this code can evaluate it correctly. You can have a try. For depth anything v2, it predicts affine-invariant disparity, and can be evaluated similarly to this code.
