### ISSUE TITLE
Downloading link

### ISSUE THREAD

**Issue by lql1233** [isl-org/MiDaS#140]
Loading weights:  weights/midas_v21-f6b98070.pt
Downloading: "https://github.com/facebookresearch/WSL-Images/archive/master.zip" to /home/liqianlin/.cache/torch/hub/master.zip

urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by shirel-gazit-healthy** [comment]
The solution is here: https://stackoverflow.com/questions/69349308/torch-hub-load-raises-httperror-http-error-404-not-found-when-loading-model
You need to change:
`
    resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")
`
to
`    resnet = torch.hub.load("facebookresearch/WSL-Images:main", "resnext101_32x8d_wsl")`

and everywhere `torch.hub.load` appears in the code.

**Comment by lql1233** [comment]
> 解决的办法是在这里：https://stackoverflow.com/questions/69349308/torch-hub-load-raises-httperror-http-error-404-not-found-when-loading-model 您需要更改[https：//开头github.com/isl-org/MiDaS/blob/master/midas/blocks.py#L115](https://github.com/isl-org/MiDaS/blob/master/midas/blocks.py#L115)： `resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")` 到 ` resnet = torch.hub.load("facebookresearch/WSL-Images:main", "resnext101_32x8d_wsl")`
> 
> 并且到处都`torch.hub.load`出现在代码中。
