### ISSUE TITLE
Could you tell me how you formulated weighted loss in terms of Multi-Task Learning as Multi-Objective Optimization repository?

### ISSUE THREAD

**Issue by InfiniteLife** [isl-org/MiDaS#141]
I've read Multi-Task Learning as Multi-Objective Optimization paper and read code in repository. For Cityscapes dataset they have 3 network heads with losses, and for each loss they calculate Frank-Wolfe coefficients. Then they have Celeba dataset, where they have 40(!) network heads for each type of class describing an image. And each head has a loss function.

But in this repository we need to calculate only Depth, and we have one loss. Then we have a few datasets. And as I understand we need to calculate Frank-Wolfe coefficient for each dataset in batch, and then weight loss for each dataset elements in batch. This logic do not fits into [repository ](https://github.com/isl-org/MultiObjectiveOptimization) . One solution I could think of is to include inside of main batch cycle new cycle that will split batch into mini-batches dataset-wise(or data loader that returns mini-batches?) and the we calculate gradients with same loss for each mini batch, calculate coefficients and summarize same loss.

Is this logic correct?
It would be awesome if you could share your `train_multi_task.py`

**Comment by pramitd** [comment]
Hi, 

Were you able to find the solution of using the same loss for a single network using the MOO?

Best Regards,
Pramit
