### ISSUE TITLE
Are you planning to provide a data generation script?

### ISSUE THREAD

**Issue by Only-bottle** [isl-org/MiDaS#165]
I wonder if the scripts that can generate datasets will be provided. 
It would be very helpful. 
Thank you very much.

**Comment by seatimx** [comment]
+1

**Comment by eyildiz-ugoe** [comment]
+1

**Comment by eyildiz-ugoe** [comment]
@Only-bottle is this really complete? Could you pass us the link of dataset generator in that case?
