### ISSUE TITLE
V3 small model

### ISSUE THREAD

**Issue by olihofmann** [isl-org/MiDaS#176]
Hi,

is planned that there will be a MiDaS V3 small model published?

**Comment by thias15** [comment]
@olihofmann, please check Swinv2-Tiny in [v3.1](https://github.com/isl-org/MiDaS/releases/tag/v3_1)

**Comment by immanueln98** [comment]
@thias15 , how can I load swinv2 via torch.hub? I get the following when following the BEiT naming convention

`RuntimeError: Cannot find callable DPT_Swinv2_T_256 in hubconf`

**Comment by alesspalma** [comment]
@immanueln98 have you found how to load swinv2 via torch.hub?
