### ISSUE TITLE
Error while loading dpt_swin2_large_384 model 

### ISSUE THREAD

**Issue by kloukiniotisandreas** [isl-org/MiDaS#219]
Hello,
I am getting errors of missing keys in state_dict and some mismatched layers when I am trying to load dpt_swin2_base_384 and any other swin model. I am using 
`python run.py --model_type dpt_swin2_base_384  --input_path input --output_path output --height 384`

**Comment by AnukritiSinghh** [comment]
hey, how did you resolve this?

**Comment by kloukiniotisandreas** [comment]
I created from scratch the env from the .yaml and it worked

**Comment by ViktorLiang** [comment]
The 'downsample' module have different size in newer version of timm. I reinstalled the  older version of timm==0.6.12 and the issue disappeared.
pip install timm==0.6.12
