### ISSUE TITLE
Bad results when running on CoreML

### ISSUE THREAD

**Issue by jankais3r** [isl-org/MiDaS#81]
Hello,

I converted the PyTorch model to CoreML, but this converted version is giving me much worse output compared to the original model. I was wondering if anyone else had better luck.

**Comparison:**
1. Original photo
2. PyTorch
3. CoreML

![MiDaS-comparison](https://user-images.githubusercontent.com/2159464/105634322-b6fdfc00-5e5d-11eb-8d89-7d2a4bc38d9e.png)

Conversion code:
```python
import torch
import coremltools as ct

torch_model = torch.hub.load('intel-isl/MiDaS', 'MiDaS')
torch_model.eval()

example_input = torch.rand(1, 3, 384, 384)
traced_model = torch.jit.trace(torch_model, example_input)
model = ct.convert(traced_model, inputs = [ct.ImageType(name = 'input_image', shape = example_input.shape)])

model.input_description['input_image'] = 'Input image'
model.output_description['1665'] = 'Inferred depth map array'

spec = model.get_spec()
ct.utils.rename_feature(spec, '1665', 'output_image')
model = ct.models.MLModel(spec)
model.save('MiDaS.mlmodel')
```

Inference code:
```python
import numpy as np
from PIL import Image, ImageOps
import coremltools as ct

input_image_path = 'demo.jpg'
model = ct.models.MLModel('MiDaS.mlmodel', useCPUOnly = True)
input_image = Image.open(input_image_path)
input_image_resized = input_image.resize((384, 384), resample = Image.LANCZOS, reducing_gap = 3)

pixels = np.asarray(input_image_resized)
pixels = pixels.astype('float32')
pixels /= 255.0

means = pixels.mean(axis=(0, 1), dtype='float32')
stds = pixels.std(axis=(0, 1), dtype='float32')
print('Means: %s, Stds: %s' % (means, stds))

targetmeans = [0.485, 0.456, 0.406]
targetstds = [0.229, 0.224, 0.225]

pixels = pixels * (targetstds/stds)
means = pixels.mean(axis=(0, 1), dtype='float32')
pixels = (pixels - means + targetmeans)
means = pixels.mean(axis=(0, 1), dtype='float32')
stds = pixels.std(axis=(0, 1), dtype='float32')
print('Means: %s, Stds: %s' % (means, stds))
print('Wanted means = [0.485, 0.456, 0.406] stds = [0.229, 0.224, 0.225]')

img = Image.fromarray((pixels * 255).astype('uint8'), 'RGB')

output_image_bytes = model.predict({'input_image': img}, useCPUOnly = True)['output_image']

depth_min = output_image_bytes.min()
depth_max = output_image_bytes.max()
out = 255 * (output_image_bytes - depth_min) / (depth_max - depth_min)
formatted = output_image_bytes[0]
formatted = (formatted * 255 / np.max(formatted)).astype('uint8')
output_image = Image.fromarray(formatted)
output_image_inverted = ImageOps.invert(output_image)
output_image_resized = output_image_inverted.resize(input_image.size)
output_image_resized.save(input_image_path[:-4] + '_depth' + input_image_path[-4:])
```

**Comment by jankais3r** [comment]
Got a slightly better result by switching around the channels before applying mean and std, but still nowhere near PyTorch's output…
```python
pixels = pixels[:, :, [0,2,1]]
```
<img width="400" src="https://user-images.githubusercontent.com/2159464/105654300-0247f700-5ebe-11eb-9d15-ec47323d964c.jpg">

**Comment by Titibo26** [comment]
Hi, I also have bad outputs with .onnx models :

<img width="648" alt="depth_try" src="https://user-images.githubusercontent.com/46820415/105987513-ab4d4800-609e-11eb-89aa-472308e3139c.PNG">

Which model are you using ? Because on all available onnx models (see : [https://github.com/intel-isl/MiDaS/issues/83#issuecomment-768154980](url) )  , only 1 give a pretty consistant output (but not as good as expected, see above).

**Comment by jankais3r** [comment]
I am using MiDaS v2.1 downloaded from PyTorch Hub.

**Comment by riteshpakala** [comment]
@jankais3r Hey!, so what I did was create the PyTorch model from the source code Model Class and the pre-trained small model for V2. Using Pytorch 1.6.

Then, I converted using CoreMLTools 4.0 

```python
import coremltools as ct
example_input = torch.rand(1, 3, 256, 256)
traced_model = torch.jit.trace(model, example_input)
model = ct.convert(traced_model, inputs = [ct.ImageType(name = 'input_image', shape = example_input.shape, scale=1/255.0)])

model.input_description['input_image'] = 'Input image'
model.output_description['1319'] = 'Inferred depth map array'
model.save('MiDaS.mlmodel')
```

Now it might prop an error, but funnily enough, re-run and it will go through. I am not exactly sure what causes this.

Anywho my results are almost 1:1 to the depicted variant in their demo. The key here is to add a pre-processing step `1/255` I feel.

Anyways, let me know if that helps.

**Comment by ghkaren** [comment]
@riteshpakala can you please share your converted model?

**Comment by HeoJinLareine** [comment]
@riteshpakala Could you share converted model ? 😂

**Comment by riteshpakala** [comment]
@ghkaren @HeoJinLareine Sorry for the late reply. I uploaded the converted model to Google Drive.

https://drive.google.com/file/d/1DMgeBpvbuK3LSYECL5OEmQRQHPZWka-3/view?usp=sharing

**Comment by jankais3r** [comment]
Thanks for sharing the converted model file. For me it produced better depth map than from my initial post, but not as good as from Torch for some reason.

Depth map from the example photo:
![demo_depth](https://user-images.githubusercontent.com/2159464/225149027-1b77032f-ec0e-4b18-8916-1622ba6d6b35.jpg)
